# Generated by Django 4.0.5 on 2022-10-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timer_promo_code_active_timer_promocode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='add_keys_interval_min',
            field=models.IntegerField(default=120),
        ),
    ]
