# Generated by Django 4.0.5 on 2022-07-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True)),
                ('img1', models.URLField(default='https://nth22.s3.ap-south-1.amazonaws.com/transperent.png', max_length=1023)),
                ('img2', models.URLField(default='https://nth22.s3.ap-south-1.amazonaws.com/transperent.png', max_length=1023)),
                ('img3', models.URLField(default='https://nth22.s3.ap-south-1.amazonaws.com/transperent.png', max_length=1023)),
                ('img4', models.URLField(default='https://nth22.s3.ap-south-1.amazonaws.com/transperent.png', max_length=1023)),
                ('level', models.IntegerField(null=True, unique=True)),
                ('tooltip', models.CharField(default=None, max_length=1023, null=True)),
                ('hints', models.TextField(default='<hints>')),
                ('gif', models.URLField(default=None, max_length=1023, null=True)),
                ('vid', models.URLField(default=None, max_length=1023, null=True)),
                ('answer', models.CharField(default='', max_length=1023)),
            ],
        ),
    ]
