# Generated by Django 4.0.5 on 2022-07-22 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_level_updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
