# Generated by Django 4.0.5 on 2022-07-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_last_level_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
