# Generated by Django 4.0.5 on 2022-07-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
