# Generated by Django 4.0.5 on 2022-10-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_question_hintcost_alter_user_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hintCost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
