# Generated by Django 4.0.5 on 2022-09-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_question_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='paidHint',
            field=models.TextField(default='<Extra hint>'),
        ),
        migrations.AddField(
            model_name='user',
            name='keys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='paidHintTaken',
            field=models.BooleanField(default=False),
        ),
    ]
