# Generated by Django 4.0.5 on 2022-07-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_question_paidhint_user_currency_user_doublertaken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doublerTakenTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
