# Generated by Django 4.0.5 on 2022-10-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_question_hintcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='is_ended',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
