# Generated by Django 4.0.5 on 2022-10-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_timer_is_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img1',
            field=models.URLField(default='https://nth22.s3.ap-south-1.amazonaws.com/rickroll-roll.png', max_length=1023),
        ),
    ]
