# Generated by Django 4.0.5 on 2022-07-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_doublertakentime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doublerTakenTime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
