# Generated by Django 4.0.5 on 2022-07-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_doublertakentime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='doublerTakenTime',
        ),
    ]
