# Generated by Django 4.0.5 on 2022-11-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_question_img1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='img1',
            field=models.URLField(default='https://nth22.s3.ap-south-1.amazonaws.com/transperent.png', max_length=1023),
        ),
    ]
