# Generated by Django 4.0.5 on 2023-05-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_answerhistory_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerhistory',
            name='answers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
