# Generated by Django 4.0.5 on 2022-09-01 18:42

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True)),
                ('img1', models.URLField(default='https://nth22.s3.ap-south-1.amazonaws.com/transperent.png', max_length=1023)),
                ('img2', models.URLField(default='https://nth22.s3.ap-south-1.amazonaws.com/transperent.png', max_length=1023)),
                ('img3', models.URLField(default='https://nth22.s3.ap-south-1.amazonaws.com/transperent.png', max_length=1023)),
                ('img4', models.URLField(default='https://nth22.s3.ap-south-1.amazonaws.com/transperent.png', max_length=1023)),
                ('level', models.IntegerField(null=True, unique=True)),
                ('tooltip', models.CharField(default=None, max_length=1023, null=True)),
                ('hints', models.TextField(default='<hints>')),
                ('gif', models.URLField(default=None, max_length=1023, null=True)),
                ('vid', models.URLField(default=None, max_length=1023, null=True)),
                ('answer', models.CharField(default='', max_length=1023)),
                ('keywords', models.TextField(blank=True, default='[]')),
                ('paidHint', models.TextField(default='<Extra hint>')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('hidden_on_leaderboard', models.BooleanField(default=False)),
                ('phone', models.IntegerField(null=True)),
                ('last_level_updated_time', models.DateTimeField(auto_now=True)),
                ('college', models.CharField(max_length=500, null=True)),
                ('paidHintTaken', models.BooleanField(default=False)),
                ('keys', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
