# Generated by Django 4.0.5 on 2022-10-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_timer_add_keys_interval_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promo_used',
            field=models.BooleanField(default=False),
        ),
    ]
