# Generated by Django 4.0.5 on 2022-10-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_promo_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='gif',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vid',
        ),
    ]
