# Generated by Django 4.0.5 on 2022-10-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_question_gif_remove_question_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img2',
            field=models.URLField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='img3',
            field=models.URLField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='img4',
            field=models.URLField(blank=True, max_length=1023, null=True),
        ),
    ]
