FROM nginx:1.17.4-alpine
# RUN apt-get update && apt-get install -y procps
RUN mkdir -p /home/app/staticfiles
# RUN cd var/ && mkdir -p /www/react
RUN rm -rf /usr/share/nginx/html/*
EXPOSE 80
# ENTRYPOINT ["nginx", "-g", "daemon off;"]
